### ISSUE TITLE
Implement and Test PredictionAlgorithm_1.java

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/wAlnut#199]
`Hypothesis`: The following is the simple biologically plausible prediction algorithm that will allow the neocortex to predict what will happen at time t=1,2,3,4,5... at t=0. 

"*Perfect lets you stall, ask more questions, do more reviews, safe it up and generally avoid doing anything that might fail or anything important. You're not in the perfect business. Stop pretending that's what the world wants from you.*" ~ [Seth Godin](http://sethgodin.typepad.com/seths_blog/2015/06/abandoning-perfection.html)

## TODO: How to score a Prediction Algorithm?

**Comment by quinnliu** [comment]
Add a section to main README.md that explains research strategy

**Comment by quinnliu** [comment]
![20150903_074023](https://cloud.githubusercontent.com/assets/2585159/9657534/feccc3b4-520f-11e5-93af-0fa3968467aa.jpg)

**Comment by quinnliu** [comment]
Possible PredictionAlgorithm_2.java:
```java
/**
     * TODO: size = ? Set a max & min with a new class? For now set same
     * as activeColumns.size()
     */
    Set<Neuron> isPredictingNeurons;
```

**Comment by quinnliu** [comment]
PredictionAlgorithm_3.java
```java
// Step 3) Which neurons should be active for the current time step?
            // Possible answer: the current list of learning neurons? This
            // is because they aren't connected to anything since they have
            // the least connected synapses
            // TODO: possible answer = only previously active neurons
            //       closeby to current learning neuron
```

**Comment by quinnliu** [comment]
CORE IDEA: The algorithm makes no assumptions about the different transformations that our world has(shifts, rotations, etc.). The algorithm ONLY says if 1 pattern follows another in time in a predictable way, then they are causally related and should have the SAME PRESENTATION in the brain.

**Comment by quinnliu** [comment]
Step 6 visual:
![20150927_234513](https://cloud.githubusercontent.com/assets/2585159/10127696/7eefca92-6574-11e5-921f-5a595c6209d6.jpg)

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/11326600/ac53d72e-913b-11e5-85bf-cff3e7bcdce5.png)

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/11457935/8ebd355e-9684-11e5-8d26-8f7600cbad7a.png)

**Comment by quinnliu** [comment]
PredictionAlgorithm_4.java

```
            // Step 2) How do you allow neuronA to predict neuronB will become
            // active in the next time step?
            // POSSIBLE ANSWER: For each learning neuron connect to all
            // previously active neurons. 1 new distal segment per learning neuron.
```

Test if connecting to half of all previously active neurons instead. (Try different percentages).

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/11458371/8c6edf84-968c-11e5-8971-57595545acf9.png)

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/11459771/3965349e-96ac-11e5-8d7d-c5404c8bcc25.png)

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/11460002/f3da1a4c-96b1-11e5-8008-7e690c26ad79.png)

**Comment by raarathi** [comment]
![img_20151129_160824](https://cloud.githubusercontent.com/assets/7343826/11460284/289da88e-96b7-11e5-943a-ebb4cec1d415.jpg)

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/11460320/3177d0b4-96b8-11e5-8294-51e3b666c61d.png)

**Comment by quinnliu** [comment]
### Step 3 with sensori-motor integration
![image](https://cloud.githubusercontent.com/assets/2585159/12080718/fff22de2-b231-11e5-866a-90b95ce0dbe6.png)

![image](https://cloud.githubusercontent.com/assets/2585159/12080720/09ea1c74-b232-11e5-9221-42442802e3a8.png)

**Comment by quinnliu** [comment]
The more I think about it the more I think we don't really need the column structure right now... it may have been a red harring. 

Notice how the highest region has the sensori-motor SDR which tells us whether or not it is a minus or a division @t=0 since the prediction is to move left at the top region right side.

**Comment by automenta** [comment]
im working with a similar sort of problem in nars https://bitbucket.org/seh/narchy/src

https://www.youtube.com/watch?v=ZbcE6hgD7WI

its logic graph is a special kind of neural network. im wondering what other kinds of neural algorithms could be added into it

https://www.youtube.com/watch?v=q_7r20htex4

**Comment by quinnliu** [comment]
@automenta Sorry was taking a break from project. I checked out your stuff and do not see how it is similar. I also see no ideas from neuroscience and just to be clear neural networks have as much ideas from neuroscience as macbooks have of a book. 

If you are serious about possibly working together we should Skype and talk further about how your algorithm predicts future input based on previous training of sequences of events. Let me know if your serious.
