### ISSUE TITLE
How WalnutiQ will pay it's developers

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/wAlnut#212]
Interested developers will be alerted through:
- leave message in VT CS facebook group
- hackNY slack
- recurse center community

Detials of how the process will work will be kept up to date here: [pay-wiki](https://github.com/WalnutiQ/wAlnut/wiki/How-to-get-paid-hourly-rate-to-code-wAlnut)

**Comment by quinnliu** [comment]
Funding source is currently only from youtube channel "quinnliuvideos" ad revenue. Monthly Funding amount payment from YouTube will show up here:
<img width="671" alt="screen shot 2015-11-05 at 12 37 55 am" src="https://cloud.githubusercontent.com/assets/2585159/10961015/0f02c778-8358-11e5-8caa-8c51d9a4e230.png">

First fund starts at 3/24/2015 for $105.16 and continues up till current day

**Comment by lxpk** [comment]
I'm interested in implementing the AI in the Unity game engine. Do you have
anyone doing that already?

**Comment by madhephaestus** [comment]
I am interested in Robotics integrations and sensory-motor feedback loops.

**Comment by quinnliu** [comment]
@lxpk We will not be doing that anytime soon. Just working on the learning algorithm and visualizing it in vision, hierarchy, and sensory-motor experiments for the forseeable future.

**Comment by quinnliu** [comment]
UPDATE: Currently already have 2 part time developers pair programming with me for free. Will use funding once I feel I need more developers.
