### ISSUE TITLE
Figure out how to pay @badlogic... using Paypal India

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/wAlnut#222]
Problem: Venmo doesn't work in India
Solution: figure out how to use Paypal @badlogicmanpreet 

@madhephaestus Kevin if you want me to pay you through paypal I can do this as well.

**Comment by quinnliu** [comment]
Link to work done by Manpreet:
1) https://github.com/WalnutiQ/wAlnut/commit/8b8e717cd20b295771ec1d0e0b6f48baa7a988f1
2) https://github.com/WalnutiQ/wAlnut/commit/e042f628aebdf727cfd7aaab4657336dc3776e45

TODO: For 2 hours $40 still needs to be paid to Manpreet

**Comment by madhephaestus** [comment]
ok, that works. kharrington@neuronrobotics.com

**Comment by quinnliu** [comment]
@madhephaestus Does paypal need a checking account?

**Comment by madhephaestus** [comment]
i talked it over with the worker cooperative i am a member of and we will be attaching the business bank account to whichever digital payment system you settle on and funneling the money into the coop.

**Comment by quinnliu** [comment]
Couldn't get Paypal working. Manpreet isn't getting paid for now.
