### ISSUE TITLE
How should science research be funded?

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/wAlnut#225]
I am curious what is the best way to fund science research...

<b>Current Method</b>:
NOTE: all blue text are links to source material.

Right now NSF use money from taxes to fund science research. Professors at universities write grants to NSF and try to convince them why they should get money to do their research.

| Source                                    | Also known as   | USD Amount from Taxpayers  | 
| --------------------------------------- | --------------------- | ---------------------------------------- | 
| National Science Foundation  | NSF                   | [7,300,000,000][1]                   
| National Institute of Health      | NIH                    | [30,100,000,000][2]                       
| Center for Disease Control and Prevention | CDC | [6,600,000,000][3]                    
| Kickstarter                               |                           | [529,000,000][4]

[1]: http://www.nsf.gov/about/ "NSF website"
[2]: http://www.nih.gov/about-nih/what-we-do/budget "NIH website"
[3]: http://www.cdc.gov/budget/documents/fy-2015-budget-request-summary-and-detail-table.pdf
[4]: https://www.kickstarter.com/year/2014/data

# TODO:
1. Who actually decides how the money gets destributed? The director? http://www.nsf.gov/news/mmg/mmg_disp.jsp?med_id=76467
2. Do you have to have a PhD to write a grant to NSF?

# Interesting Notes
1. Director of NIH [Francis Collins believes in evolution and a Christian god][1] = WTF. I was hoping he was faking it but it appears not to be so since he wrote a book about being a [theistic evolutionist][2]. 
2. https://www.nationalpriorities.org/budget-basics/federal-budget-101/spending/

[1]: https://en.wikipedia.org/wiki/Francis_Collins
[2]: https://en.wikipedia.org/wiki/The_Language_of_God

**Comment by MrBly** [comment]
Hey! Just popping in to say that a lot of small research groups get funded through "Broad Agency Announcements" and, if you become a small business, "Small Business Research Initiative" grant (thought it might be a bit soon for that). A Broad Agency Announcement might be a good bet, though. You look for some government organization that needs something that your goals come close to and write them suggesting that you'll fulfill their announcement. One of those might not fully fund you, but it may certainly help.

**Comment by quinnliu** [comment]
Do you know where to find Broad Agency announcements that would want A.I. research? Also would the people that fund it get to keep all the research?

**Comment by MrBly** [comment]
The funding is per contract, so the contracted entity, I believe, retains property of the research, but, of course, the contracting entity gets to use it. Most BAAs are through the military, and the Army does quite a few: http://www.arl.army.mil/www/default.cfm?page=8

Also see the following for some law about BAAs: https://www.acquisition.gov/sites/default/files/current/far/html/Subpart%2035_0.html#wp1085187

A web search for "broad agency announcement" will get you to a number of databases full of them. The army page also has a few more suggestions on how to get funding (including the aforementioned SBIR).

**Comment by quinnliu** [comment]
I read "It is anticipated that the awards will be made in the form of grants to universities. " This doesn't seem applicable to this project.

**Comment by MrBly** [comment]
Anticipated, sure, but not exclusive. In the long run, if you don't want to attach your research to a university, I suggest becoming a small business centered around research and development.

**Comment by quinnliu** [comment]
Closing this for now so I can think of other ways to fund this project besides just donations and ad revenue from my youtube channel.

**Comment by quinnliu** [comment]
Actually want to think about this some more...

**Comment by quinnliu** [comment]
@MrBly I don't appreciate you telling me what I should do and wasting my time with links that are very confusing to navigate. If your going to contribute something to this project do it seriously. I don't want to hear your random opinions that are just talk and have no experience and action behind them.
