### ISSUE TITLE
Propose using Gitter for tighter looped discussions

### ISSUE THREAD

**Issue by madhephaestus** [WalnutiQ/wAlnut#241]
Gitter is a slack/IRC type service based around Github logins and groups. 

https://gitter.im/WalnutiQ

The main advantage is that it adds discussion functionality without creating a new and separate login to do so.

**Comment by quinnliu** [comment]
@madhephaestus nice idea but I feel like our project is not popular enough for this. For instance no one ever comments on the new issues I create for this wAlnut repo. Once people start doing that I will add this to wAlnut. sound gucci?
