### ISSUE TITLE
Attention

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/wAlnut#245]
Attention goes to the most unexpected thing?

Attention goes to the best predicted thing?

**Comment by madhephaestus** [comment]
maybe there is more than one type of attention, think about the 4 basic drives from biology: https://en.wikipedia.org/wiki/Four_Fs_(evolution) . Food might look for predicted, but fight/flight might send attention to unexpected. Just a thought...

**Comment by quinnliu** [comment]
moved idea to #260
