### ISSUE TITLE
GSOC?

### ISSUE THREAD

**Issue by emcenrue** [WalnutiQ/wAlnut#253]
IF jobs/time permits someone to be a mentor, then perhaps this
https://developers.google.com/open-source/gsoc/

will be useful?

**Comment by quinnliu** [comment]
@emcenrue this looks like a distraction to me. Do I get funding from Google to pay a 18 year old to code based on what I teach him?

**Comment by quinnliu** [comment]
If you want to register this project please feel free to. Otherwise I feel I need to focus on the current vision experiment and prediction algorithm testing :)

**Comment by emcenrue** [comment]
nope, just thought that it could possibly assist in contribution docs improvement (by decreasing barrier to entry), since it seems like contribution documentation is already a goal in the process of this project
