### ISSUE TITLE
when u want to simulate imagination

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/wAlnut#271]
How do you simulate imagination?
- ontop of the cortical common learning algorithm

If you are thinking about someone you can imagine what they are doing
- this is very important to building conciousness

**Comment by quinnliu** [comment]
experiment 1) have it look at animals and then have it look at clouds

**Comment by quinnliu** [comment]
From Dileeps talk [slides](http://futureoflife.org/data/PDF/dileep_george.pdf) and [video of beginning slides](https://www.youtube.com/watch?v=NPtAIVieh4k)

**Comment by quinnliu** [comment]
<img width="415" alt="screen shot 2016-08-01 at 9 34 49 pm" src="https://cloud.githubusercontent.com/assets/2585159/17295658/cb1b203e-582f-11e6-875e-cb0976ae1edb.png">

**Comment by quinnliu** [comment]
<img width="847" alt="screen shot 2016-08-01 at 9 35 02 pm" src="https://cloud.githubusercontent.com/assets/2585159/17295668/d7033580-582f-11e6-99d1-0859d21d59c8.png">

**Comment by quinnliu** [comment]
<img width="648" alt="screen shot 2016-08-01 at 9 35 31 pm" src="https://cloud.githubusercontent.com/assets/2585159/17295686/e619582e-582f-11e6-99c3-c45a684f68fd.png">

HOLY SHIT THIS IS FUCKING AMAZING!!!!!!!!!!!!!!!!!!!!

**Comment by markroxor** [comment]
@syeddanish41
