### ISSUE TITLE
when u want to keep track of progress for building visualization tool of Dileep's HTM model

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/wAlnut#280]
The best visualization tool for walnut is the key. On metrics that actually matter. This will be a better version of a fMRI. What we are missing in neuroscience is a tool to visualize the brain very clearly so we can experiment with it and optimize it. 

![dsc02329](https://cloud.githubusercontent.com/assets/2585159/17363918/cc735452-59af-11e6-88cb-1935f86accf0.jpg)

**Comment by quinnliu** [comment]
Question: How to build visualizer input and output

Easy solution have model print out a log of updates and then have visualizer process that formatted information to create a time step visualizer of the model through time.

**Comment by quinnliu** [comment]
<img width="406" alt="screen shot 2016-09-28 at 12 40 55 pm" src="https://cloud.githubusercontent.com/assets/2585159/18910559/d4e4d0ee-8578-11e6-878d-849c96e599ba.png">
High level JSON structure of model in at timestep t = 0

**Comment by quinnliu** [comment]
going to write visualization tool in new repo here: https://github.com/WalnutiQ/toph

**Comment by quinnliu** [comment]
okay realizing I made a mistake by starting with boilerplate. Just going to start with D3.js tutorial here: http://alignedleft.com/tutorials/d3/fundamentals

**Comment by quinnliu** [comment]
D3.js is the shit

**Comment by quinnliu** [comment]
![screen shot 2016-09-29 at 5 33 19 pm](https://cloud.githubusercontent.com/assets/2585159/18960672/dc83bcf0-866a-11e6-8d59-e0f65a1f8232.png)

**Comment by quinnliu** [comment]
TODO: http://alignedleft.com/tutorials/d3/an-svg-primer

**Comment by quinnliu** [comment]
This would be an awesome animation of the markov graph!!!! TODO: http://bl.ocks.org/rkirsling/5001347

**Comment by quinnliu** [comment]
finished multi line chart: https://github.com/WalnutiQ/toph
Now just need to generate data for memory sizes of digits experiment

**Comment by quinnliu** [comment]
TODO:
- [ ] write data to `node_averages.tsv` file

**Comment by quinnliu** [comment]
CONTEXT:

- [ ] write data to `node_averages.tsv` file
   + [ ] add button so that you select the file you want to show data of. For example a drop down
           that allows you to pick the file: `classify_digits_experiment.zip` to show data of would be
           sick

**Comment by quinnliu** [comment]
http://bl.ocks.org/rkirsling/5001347

**Comment by markroxor** [comment]
@devojoyti
