### ISSUE TITLE
Generate input dataset.

### ISSUE THREAD

**Issue by markroxor** [WalnutiQ/wAlnut#315]
- [x] draw all different images in photoshop for 32 by 32 pixels
- [x] add them to repo and generate t=0.bmp -> t=100.bmp of images moving from top left to bottom right horizontally first
  - t=0 -> t=503 is digit 0 `python generate_data.py 'data/categories/zero.png' '9' '12' '0' '503' 'data/unzipped_training_video'`
  - t=504 -> t=911 is bed `python generate_data.py 'data/categories/bed.png' '16' '9' '504' '911' 'data/unzipped_training_video'`
  - t=912 -> 1268 is cat `python generate_data.py 'data/categories/cat.png' '16' '12' '912' '1268' 'data/unzipped_training_video'`
  - t=1269 -> 1492 is computer `python generate_data.py 'data/categories/computer.png' '19' '17' '1269' '1492' 'data/unzipped_training_video'`
  - t=1493->1792 is dog `python generate_data.py 'data/categories/dog.png' '18' '13' '1493' '1792' 'data/unzipped_training_video'`
- [x] save entire image dataset into a .zip file 
- [x] push the .zip file into wAlnut repo branch `develop`

**Comment by quinnliu** [comment]
<img width="713" alt="screen shot 2016-12-10 at 10 57 27 am" src="https://cloud.githubusercontent.com/assets/2585159/21074819/f988279c-bec7-11e6-99bb-49abb2cb49b4.png">

**Comment by quinnliu** [comment]
<img width="700" alt="screen shot 2016-12-10 at 11 32 04 am" src="https://cloud.githubusercontent.com/assets/2585159/21074963/4e4583b6-becc-11e6-9b89-54ec51e48ce7.png">

**Comment by quinnliu** [comment]
Generated about ~2000 images with 5 categories video_1.zip in wAlnut datasets which is enough for initial testing.
