### ISSUE TITLE
understand Dileep's talk on AGI

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/wAlnut#322]
- [ ] [talk](http://events.technologyreview.com/video/watch/dileep-george-vicarious-ai-work/)

**Comment by markroxor** [comment]
The video?

**Comment by quinnliu** [comment]
ya it's a good introduction

**Comment by quinnliu** [comment]
click on "talk" it's a link to the video

**Comment by markroxor** [comment]
Everyone has seen it
