### ISSUE TITLE
create a github.io page

### ISSUE THREAD

**Issue by markroxor** [WalnutiQ/wAlnut#325]
Create a gihub.io page for walnut, following this - http://cmusatyalab.github.io/openface/

**Comment by quinnliu** [comment]
again I think this is something that is a red haring. It seems important to do but is not important to do. I think https://github.com/WalnutiQ/wAlnut is fine for now

**Comment by markroxor** [comment]
It was intended for serving js files. For a better and instant visualization. I think it is necessary for that.

**Comment by quinnliu** [comment]
@markroxor but to create the visualizations I think we need to host it on our own server so we can also use Redux and React.js. If github.io supports that I am all for it. However I don't believe it does.

**Comment by markroxor** [comment]
You are totally right. Github pages only serve static content. Let's keep this on hold.

**Comment by quinnliu** [comment]
not important right now focus on recaptcha
