### ISSUE TITLE
Using cython

### ISSUE THREAD

**Issue by markroxor** [WalnutiQ/wAlnut#330]
The execution speed can be throttled by using C implementation of python - [Cython](https://www.cython.org)

**Comment by quinnliu** [comment]
I think execution speed of any of the algorithms is a red haring. It seems important but is not important right now. It may be in the future. I vote we don't use cython right now to focus on a faster development time

**Comment by markroxor** [comment]
Again it is priority #3. I too vote for faster development. It's just something we might need in future.

**Comment by quinnliu** [comment]
not important right now focus on recaptcha
