### ISSUE TITLE
RESEARCH: The Case Against Reality

### ISSUE THREAD

**Issue by markroxor** [WalnutiQ/wAlnut#347]
https://www.theatlantic.com/science/archive/2016/04/the-illusion-of-reality/479559/
A one on one about the perception of reality with Donald D. Hoffman, a professor of cognitive science at the University of California.
> Hoffman has spent the past three decades studying perception, artificial intelligence, evolutionary game theory and the brain, and his conclusion is a dramatic one: The world presented to us by our perceptions is nothing like reality.

**Comment by quinnliu** [comment]
I agree with his conclusion but it's also pretty obvious since the brain makes a lot of assumptions. Does he make any other points? Mind summarizing them? Thanks

**Comment by markroxor** [comment]
Off-topic - [This](https://www.youtube.com/watch?v=L45Q1_psDqk) video by Vsauce titled 'Is Anything Real?' is great.

**Comment by mgifford** [comment]
this is quite good https://youarenotsosmart.com/2016/12/02/yanss-090-questioning-the-nature-of-reality-with-cognitive-scientist-donald-hoffman/
